title: Computational Photography by Mohamed Debbagh
author: Mohamed Debbagh
email: mohamed.debbagh@mail.mcgill.ca
description: >-
  Computationally generated photograph. These images were generated for the ECSE 544 at McGill University

social:
  twitter: moha7108
  facebook: 
  instagram: moha7108
  github: moha7108
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
